# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  keycloak:
    url: ""
    name: keycloak
    service:
      type: http
      port: 80
      
db:
  deployPostgres: true
  uri: ""
  name: querypostgresql
  port: 5432
    
## Allows the specification of additional environment variables
extraEnv: |
  # - name: ACT_KEYCLOAK_URL
  #   valueFrom:
  #     configMapKeyRef:
  #       name: {{ .Release.Name }}-keycloak-http
  #       key: expose-keycloak-service-key

javaOpts:
  xmx: 1024m
  xms: 512m
  other: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
  
replicaCount: 1
image:
  repository: docker.io/introproventures/activiti-cloud-query-graphql-query
  tag: 1.0.57
  pullPolicy: IfNotPresent
service:
  name: graphql-query
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.name: "graphql"
    fabric8.io/ingress.path: "/"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 1
    memory: 2048Mi
  requests:
    cpu: 1
    memory: 1024Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10